export const SUPABASE_URL = "https://juywatmqwykgdjfqexho.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eXdhdG1xd3lrZ2RqZnFleGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDQxNjAsImV4cCI6MjA1NzQ4MDE2MH0.BgGwmqHC7M6NBeJmAMhZJ746cl2T6rgkqUDUqBj7iBw";
