[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/auth/login.html"
  status = 200

# Add sitemap redirect
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/generate-sitemap"
  status = 200

[build]
  functions = "netlify/functions"

[functions]
  included_files = ["js/services/rss.js"]

[functions.update-podcasts]
  schedule = "@daily"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Add function redirect for RSS proxy
[[redirects]]
  from = "/rss-proxy"
  to = "/.netlify/functions/rss-proxy"
  status = 200
